language: python
python:
  - "2.7"
sudo: false
install: 
  - pip install .
  - pip install coveralls
before_script:
  - evennia --init dummy
  - cd dummy
  - evennia migrate
script:
  - coverage run --omit=*.virtualenvs*,*virtualenv* bin/unix/evennia test evennia  
after_success:
  - coveralls
